### ISSUE TITLE
Creating custom wizard layout leads to nullpointerexception

### ISSUE THREAD

**Issue by torgash-ivanblch** [Nimrodda/WizarDroid#51]
Here's my code of BasicWizardLayout-inherited class
```
package im.point.torgash.mecicinealert;

import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;

import org.codepond.wizardroid.WizardFlow;
import org.codepond.wizardroid.layouts.BasicWizardLayout;

import im.point.torgash.mecicinealert.loginwizard.LoginWizardStep0;
import im.point.torgash.mecicinealert.loginwizard.LoginWizardStep1;
import im.point.torgash.mecicinealert.loginwizard.LoginWizardStep2;
import im.point.torgash.mecicinealert.loginwizard.LoginWizardStep3;

/**
 * Created by ivanblch on 11.01.2015.
 */
public class LoginWizardLayout extends BasicWizardLayout {
    Button nextButton;
    Button previousButton;
    /**
     * Note that initially BasicWizardLayout inherits from {@link android.support.v4.app.Fragment} and therefore you must have an empty constructor
     */
    public LoginWizardLayout() {
        super();
    }
    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        View wizardLayout = inflater.inflate(R.layout.my_wizard_layout, container, false);
        nextButton = (Button) wizardLayout.findViewById(R.id.wizard_next_button);
        nextButton.setOnClickListener(this);
        previousButton = (Button) wizardLayout.findViewById(R.id.wizard_previous_button);
        previousButton.setOnClickListener(this);

        return wizardLayout;
    }
    //You must override this method and create a wizard flow by
    //using WizardFlow.Builder as shown in this example
    @Override
    public WizardFlow onSetup() {
        /* Optionally, you can set different labels for the control buttons
        setNextButtonLabel("Advance");
        setBackButtonLabel("Return");
        setFinishButtonLabel("Finalize"); */
        setNextButtonText("Далее");
        setBackButtonText("Назад");
        setFinishButtonText("Завершить");

        return new WizardFlow.Builder()
                .addStep(LoginWizardStep0.class)
                .addStep(LoginWizardStep1.class)           //Add your steps in the order you want them
                .addStep(LoginWizardStep2.class)           //to appear and eventually call create()
                .addStep(LoginWizardStep3.class)
                .create();                              //to create the wizard flow.
    }
    @Override
    public void onClick(View v) {
        switch(v.getId()) {
            case R.id.wizard_next_button:
                //Tell the wizard to go to next step
                wizard.goNext();
                break;
            case R.id.wizard_previous_button:
                //Tell the wizard to go back one step
                wizard.goBack();
                break;
        }
        updateWizardControls();
    }

    private void updateWizardControls() {
        previousButton.setEnabled(!wizard.isFirstStep());
        nextButton.setText(wizard.isLastStep()
                ? R.string.action_finish
                : R.string.action_next);
    }
}
```
And this is what I get in LogCat: 
```
 java.lang.RuntimeException: Unable to resume activity {im.point.torgash.mecicinealert/im.point.torgash.mecicinealert.MainActivity}: java.lang.NullPointerException
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2964)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2993)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5299)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
            at org.codepond.wizardroid.layouts.BasicWizardLayout.updateWizardControls(BasicWizardLayout.java:111)
            at org.codepond.wizardroid.layouts.BasicWizardLayout.onResume(BasicWizardLayout.java:65)
            at android.support.v4.app.Fragment.performResume(Fragment.java:1829)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:983)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
            at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
            at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:1927)
            at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:444)
            at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:433)
            at android.support.v7.app.ActionBarActivity.onPostResume(ActionBarActivity.java:140)
            at android.app.Activity.performResume(Activity.java:5356)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2950)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2993)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2395)
            at android.app.ActivityThread.access$800(ActivityThread.java:151)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
            at android.os.Handler.dispatchMessage(Handler.java:110)
            at android.os.Looper.loop(Looper.java:193)
            at android.app.ActivityThread.main(ActivityThread.java:5299)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:825)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:641)
            at dalvik.system.NativeStart.main(Native Method)

```

As you can see, LogCat doesn't mention my own Java code errors: the exception is thrown in your class. Is there a way to fix this?

**Comment by torgash-ivanblch** [comment]
Oh, I've investigated what's happened. Could you please change your BasicWizardLayout.updateWizardControls() method from private to public? It should be overridden. Otherwise, we can't make it see new Button variables initialized in overridden onCreate() method.

**Comment by torgash-ivanblch** [comment]
Made a pullrequest so that you could just accep it

**Comment by Nimrodda** [comment]
`BasicWizardLayout`'s layout isn't meant to be extensible (inherited from) and that's done by design. There's a reason why `updateWizardControls()` is private, and so do `nextButton` and `previousButton`. If you want to create your own layout please see [Creating Custom Wizard Layout](https://github.com/Nimrodda/WizarDroid/wiki/Creating-Custom-Wizard-Layout).

**Comment by torgash-ivanblch** [comment]
Seems like I've inherited the wrong class. What surprises me is why this "composition" works perfectly if I just change this method to public in the source :)
sorry for that
