### ISSUE TITLE
java.lang.ClassCastException: android.support.v7.widget.AppCompatAutoCompleteTextView cannot be cast to java.io.Serializable

### ISSUE THREAD

**Issue by vishnuchd** [Nimrodda/WizarDroid#87]
I am having Autocomplete textview which get suggestions from a webservice on step1. Step 1 also have a checkbox when i move to second Step i get the following error

FATAL EXCEPTION: main
                                                                       java.lang.ClassCastException: android.support.v7.widget.AppCompatAutoCompleteTextView cannot be cast to java.io.Serializable
                                                                           at org.codepond.wizardroid.persistence.ContextManagerImpl.persistStepContext(ContextManagerImpl.java:130)
                                                                           at org.codepond.wizardroid.Wizard.processStepBeforeChange(Wizard.java:167)
                                                                           at org.codepond.wizardroid.Wizard.access$500(Wizard.java:25)
                                                                           at org.codepond.wizardroid.Wizard$2.onPageScrollStateChanged(Wizard.java:123)
                                                                           at android.support.v4.view.ViewPager.dispatchOnScrollStateChanged(ViewPager.java:1863)
                                                                           at android.support.v4.view.ViewPager.setScrollState(ViewPager.java:460)
                                                                           at android.support.v4.view.ViewPager.access$000(ViewPager.java:91)
                                                                           at android.support.v4.view.ViewPager$3.run(ViewPager.java:253)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:749)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:562)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:531)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:735)
                                                                           at android.os.Handler.handleCallback(Handler.java:730)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:92)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5103)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:525)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by Nimrodda** [comment]
Reading the exception I have a feeling you aren't using the `@ContextVariable` annotation the right way.
Could you please paste the code snippet containing the step's fields which are annotated with  `@ContextVariable`?

**Comment by Nimrodda** [comment]
Closing due to inactivity of the reporter.
